### PR TITLE
Typing update for Python3.8 and above, Ephemeral messages.

### PR DESCRIPTION
**Pull request by SZOKOZ**

### CODE REVIEW

**Comment by sooswastaken** [comment]
Thanks!

**Comment by SZOKOZ** [comment]
> Thanks!

Your welcome. This package is very useful to me.

**Comment by sooswastaken** [comment]
I will update pypi after I go to sleep with v0.0.5. 👍

**Comment by sooswastaken** [comment]
I just woke up! I updated pypi.

**Pull request merged**
